services:
  - type: web
    name: projetores-demo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: APP_SECRET_KEY
        generateValue: true
